### ISSUE TITLE
SPF Record not updated

### ISSUE THREAD

**Issue by iamra** [danodemano/cloudflare-bulk-ip-update#1]
Thank you for an excellent utility, worked flawlessly.
One thing I noticed however, is that an SPF record on my domain was not updated.
If I find out where in your code (or the API) this is missing, I will update.

**Comment by danodemano** [comment]
Hi @sacredwebsite,

Honestly SFP updates were never even a part of the design.  There can be so many variants on the way people define IP addresses/subnets I figured it was always best to leave those up to a manual change.  If this is something you would need however I can see about adding it into the code.  Cheers!

Dan

**Comment by iamra** [comment]
@danodemano no worries, I do not use it often. I was mainly wishing to bring notice to this point. Thank you for your time and energy!
